### ISSUE TITLE
Consider enabling the discussions feature

### ISSUE THREAD

**Issue by soupertonic** [JAForbes/S#15]
I've got a few questions regarding S.js and how it may play together with Mithril.js but I don't wanna litter the issues section. How about enabling the discussion feature?

Cheers.

**Comment by JAForbes** [comment]
@soupertonic right now this is very much a research project, I'm a bit concerned enabling discussions will encourage people to use this repo in their projects, but its not stable at all yet.   Do you think I should still enable discussions given that concern?
